services:
  redis-cache:
    image: redis:7.0.8-alpine3.17
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --save 20 1
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local