column_mapping = {
    'campaign_id': 'campaign._id',
    'traffic_source_id': 'traffic_source._id',
    'visitor_device_browser': 'visitor.device.browser',
    'visitor_device_hardware_family': 'visitor.device.hardware.family',
    'visitor_device_hardware_model': 'visitor.device.hardware.model',
    'visitor_device_hardware_vendor': 'visitor.device.hardware.vendor',
    'visitor_device_os_family': 'visitor.device.os.family',
    'visitor_device_os_vendor': 'visitor.device.os.vendor',
    'visitor_device_os_version': 'visitor.device.os.version',
    'visitor_device_type': 'visitor.device.type',
    'visitor_geo_location_cityName': 'visitor.geo_location.cityName',
    'visitor_geo_location_connection_type': 'visitor.geo_location.connection_type',
    'visitor_geo_location_countryCode': 'visitor.geo_location.countryCode',
    'visitor_geo_location_isp': 'visitor.geo_location.isp',
    'visitor_geo_location_regionName': 'visitor.geo_location.regionName',
}

columns_df = [
    'campaign_id',
    'traffic_source_id',
    'visitor_device_browser',
    'visitor_device_hardware_family',
    'visitor_device_hardware_model',
    'visitor_device_hardware_vendor',
    'visitor_device_os_family',
    'visitor_device_os_vendor',
    'visitor_device_os_version',
    'visitor_device_type',
    'visitor_geo_location_cityName',
    'visitor_geo_location_connection_type',
    'visitor_geo_location_countryCode',
    'visitor_geo_location_isp',
    'visitor_geo_location_regionName',
]

columns_df_total = [
    'campaign_id',
    'traffic_source_id',
    'visitor_device_browser',
    'visitor_device_hardware_family',
    'visitor_device_hardware_model',
    'visitor_device_hardware_vendor',
    'visitor_device_os_family',
    'visitor_device_os_vendor',
    'visitor_device_os_version',
    'visitor_device_type',
    'visitor_geo_location_cityName',
    'visitor_geo_location_connection_type',
    'visitor_geo_location_countryCode',
    'visitor_geo_location_isp',
    'visitor_geo_location_regionName',
    'visitor_tokens_adh',
    'visitor_tokens_cadid',
    'visitor_tokens_adi',
    'converted_yes',
    'converted_no'
]